--------------------------------------------------------
--  已建立檔案 - 星期二-十月-13-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table F_ARTICLE
--------------------------------------------------------

  CREATE TABLE "III_TEAM_DBA"."F_ARTICLE" 
   (	"ART_CONTENT" CLOB, 
	"ART_CRE_TIME" DATE, 
	"ART_USERID" VARCHAR2(255 BYTE), 
	"ART_COMM_NUM" NUMBER(*,0), 
	"ART_VIEW" NUMBER(*,0), 
	"ART_ID" NUMBER(*,0), 
	"ART_TYPE_ID" NUMBER, 
	"ART_TITLE" VARCHAR2(255 BYTE), 
	"ART_PIC" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ART_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "III_TEAM_DBA"."F_ARTICLE"."ART_TYPE_ID" IS '文章分類';
--------------------------------------------------------
--  DDL for Index F_ARTICLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "III_TEAM_DBA"."F_ARTICLE_PK" ON "III_TEAM_DBA"."F_ARTICLE" ("ART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ART_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "III_TEAM_DBA"."ART_ID_TRIGGER" 
   before insert on "III_TEAM_DBA"."F_ARTICLE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ART_ID" is null then 
         select ARTID_SEQUENCE.nextval into :NEW."ART_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "III_TEAM_DBA"."ART_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table F_ARTICLE
--------------------------------------------------------

  ALTER TABLE "III_TEAM_DBA"."F_ARTICLE" MODIFY ("ART_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_ARTICLE" MODIFY ("ART_CRE_TIME" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_ARTICLE" MODIFY ("ART_USERID" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_ARTICLE" MODIFY ("ART_ID" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_ARTICLE" MODIFY ("ART_TITLE" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_ARTICLE" ADD CONSTRAINT "F_ARTICLE_PK" PRIMARY KEY ("ART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table F_ARTICLE
--------------------------------------------------------

  ALTER TABLE "III_TEAM_DBA"."F_ARTICLE" ADD CONSTRAINT "ARTCILETYPE" FOREIGN KEY ("ART_TYPE_ID")
	  REFERENCES "III_TEAM_DBA"."F_ART_TYPE" ("TYPE_ID") ENABLE;
  ALTER TABLE "III_TEAM_DBA"."F_ARTICLE" ADD CONSTRAINT "USERID" FOREIGN KEY ("ART_USERID")
	  REFERENCES "III_TEAM_DBA"."ACCOUNT" ("USERNAME") DISABLE;
