--------------------------------------------------------
--  已建立檔案 - 星期二-十月-13-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table F_COMMENT
--------------------------------------------------------

  CREATE TABLE "III_TEAM_DBA"."F_COMMENT" 
   (	"COM_ID" NUMBER, 
	"COM_CONTENT" VARCHAR2(255 BYTE), 
	"COM_ART_ID" NUMBER, 
	"COM_USER_ID" VARCHAR2(255 BYTE), 
	"COM_DATE" DATE, 
	"COM_PIC" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index F_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "III_TEAM_DBA"."F_COMMENT_PK" ON "III_TEAM_DBA"."F_COMMENT" ("COM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger COMMENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "III_TEAM_DBA"."COMMENT_TRIGGER" 
   before insert on "III_TEAM_DBA"."F_COMMENT" 
   for each row 
begin  
   if inserting then 
      if :NEW."COM_ID" is null then 
         select COMID_SEQUENCE.nextval into :NEW."COM_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "III_TEAM_DBA"."COMMENT_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table F_COMMENT
--------------------------------------------------------

  ALTER TABLE "III_TEAM_DBA"."F_COMMENT" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_COMMENT" MODIFY ("COM_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_COMMENT" MODIFY ("COM_ART_ID" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_COMMENT" MODIFY ("COM_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_COMMENT" MODIFY ("COM_DATE" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."F_COMMENT" ADD CONSTRAINT "F_COMMENT_PK" PRIMARY KEY ("COM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table F_COMMENT
--------------------------------------------------------

  ALTER TABLE "III_TEAM_DBA"."F_COMMENT" ADD CONSTRAINT "ART_ID" FOREIGN KEY ("COM_ART_ID")
	  REFERENCES "III_TEAM_DBA"."F_ARTICLE" ("ART_ID") ENABLE;
  ALTER TABLE "III_TEAM_DBA"."F_COMMENT" ADD CONSTRAINT "COM_USERID" FOREIGN KEY ("COM_USER_ID")
	  REFERENCES "III_TEAM_DBA"."ACCOUNT" ("USERNAME") DISABLE;
