--------------------------------------------------------
--  DDL for Table RESTAURANT
--------------------------------------------------------

  CREATE TABLE "III_TEAM_DBA"."RESTAURANT" 
   (  "R_SN" NUMBER, 
  "NAME" VARCHAR2(255 BYTE), 
  "ADDRESS" VARCHAR2(255 BYTE), 
  "OPENTIME" VARCHAR2(255 BYTE), 
  "DESCRIPTION" VARCHAR2(1024 BYTE), 
  "TRANSPORTATION" VARCHAR2(1024 BYTE), 
  "TYPE" VARCHAR2(255 BYTE), 
  "RATING" NUMBER(10,7), 
  "REGION" VARCHAR2(255 BYTE), 
  "PICTURE" VARCHAR2(255 BYTE), 
  "SERVICEINFO" VARCHAR2(1024 BYTE), 
  "BOOKING_ID" VARCHAR2(255 BYTE), 
  "ACCOUNT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESTAURANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "III_TEAM_DBA"."RESTAURANT_PK" ON "III_TEAM_DBA"."RESTAURANT" ("R_SN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence RESTAURANT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "III_TEAM_DBA"."RESTAURANT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL for Trigger RESTAURANT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "III_TEAM_DBA"."RESTAURANT_TRG" 
BEFORE INSERT ON RESTAURANT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.R_SN IS NULL THEN
      SELECT RESTAURANT_SEQ.NEXTVAL INTO :NEW.R_SN FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "III_TEAM_DBA"."RESTAURANT_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table RESTAURANT
--------------------------------------------------------

  ALTER TABLE "III_TEAM_DBA"."RESTAURANT" MODIFY ("R_SN" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."RESTAURANT" ADD CONSTRAINT "RESTAURANT_PK" PRIMARY KEY ("R_SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESTAURANT
--------------------------------------------------------

  ALTER TABLE "III_TEAM_DBA"."RESTAURANT" ADD CONSTRAINT "RESTAURANT_FK1" FOREIGN KEY ("ACCOUNT")
    REFERENCES "III_TEAM_DBA"."ACCOUNT" ("USERNAME") ENABLE;
