--------------------------------------------------------
--  已建立檔案 - 星期六-十月-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IDENTITY
--------------------------------------------------------

  CREATE TABLE "III_TEAM_DBA"."IDENTITY" 
   (	"ID" NUMBER(1,0), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDENTITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "III_TEAM_DBA"."IDENTITY_PK" ON "III_TEAM_DBA"."IDENTITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table IDENTITY
--------------------------------------------------------

  ALTER TABLE "III_TEAM_DBA"."IDENTITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "III_TEAM_DBA"."IDENTITY" ADD CONSTRAINT "IDENTITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
